name: Publish in Microsoft Marketplace
on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  prepare-environment:
    name: 'Get Release Version'
    runs-on: ubuntu-latest
    environment: publish
    outputs:
      RELEASE_VERSION: ${{ steps.getVersion.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'
      - id: getVersion
        run: |
          echo "version=$(node -pe "require('./package.json').version")" >> $GITHUB_OUTPUT
      - run: echo "Version is ${{ steps.getVersion.outputs.version }}"

  publish:
    needs: ['prepare-environment']
    runs-on: ubuntu-latest
    env:
      VSCE_PERSONAL_ACCESS_TOKEN: ${{ secrets.VSCE_PERSONAL_ACCESS_TOKEN }}
      PUBLISH_VERSION: ${{ needs.prepare-environment.outputs.RELEASE_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'main'
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION || 'lts/*' }}
      - name: Install dependencies
        run: npm ci
      - name: Package extension
        run: npx vsce package -o ./Salesforce-Tableau-Semantics-${{ env.PUBLISH_VERSION }}.vsix
      - name: Publish to VS Code Marketplace
        run: npx vsce publish --skip-duplicate --pat "${{ env.VSCE_PERSONAL_ACCESS_TOKEN }}" --packagePath ./Salesforce-Tableau-Semantics-${{ env.PUBLISH_VERSION }}.vsix
      - name: Upload vsix to GitHub Release
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload "v${{ env.PUBLISH_VERSION }}" ./Salesforce-Tableau-Semantics-${{ env.PUBLISH_VERSION }}.vsix --clobber
