name: Publish in Open VSX Registry
on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  prepare-environment:
    name: 'Get Release Version'
    runs-on: ubuntu-latest
    environment: publish
    outputs:
      RELEASE_VERSION: ${{ steps.getVersion.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'
      - id: getVersion
        run: |
          echo "version=$(node -pe "require('./package.json').version")" >> $GITHUB_OUTPUT
      - run: echo "Version is ${{ steps.getVersion.outputs.version }}"

  publish:
    needs: ['prepare-environment']
    runs-on: ubuntu-latest
    env:
      OVSX_PAT: ${{ secrets.IDEE_OVSX_PAT }}
      PUBLISH_VERSION: ${{ needs.prepare-environment.outputs.RELEASE_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: 'main'
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION || 'lts/*' }}
      - name: Install dependencies
        run: npm ci
      - name: Package extension
        run: npx vsce package -o ./Salesforce-Tableau-Semantics-${{ env.PUBLISH_VERSION }}.vsix
      - name: Publish to Open VSX Registry
        run: npx ovsx publish ./Salesforce-Tableau-Semantics-${{ env.PUBLISH_VERSION }}.vsix --skip-duplicate -p "${{ env.OVSX_PAT }}"
